import NavBar from "@/components/NavBar";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "The Curiousity Collective",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-atyp flex min-h-screen flex-col justify-between w-full h-full">
      <div className="flex flex-col grow mx-auto justify-between max-w-9xl w-full h-full border">
      <NavBar />
      {children}
      <Footer />
      </div>
      </body>
    </html>
  );
}
